version: '3.5'
services:
  db-deliveryit:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - proxy
    env_file:
      - ./env_files/.env.prod.db

  api-deliveryit:
    container_name: api-deliveryit
    build: ./api
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - api_data:/docker_api
    networks:
      - proxy
    env_file:
      - ./env_files/.env.prod.web
    depends_on:
      - db-deliveryit

  nginx-deliveryit:
    container_name: nginx-deliveryit
    build: ./nginx
    restart: always
    volumes:
      - api_data:/docker_api
      - ./log:/var/log/nginx
    networks:
      - proxy
    depends_on:
      - api-deliveryit
    env_file:
      - ./env_files/.env.prod.nginx


volumes:
  api_data:
  postgres_data:

networks:
  proxy:
    external:
      name: nginx-proxy