# Generated by Django 3.1.7 on 2021-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('valor_original', models.FloatField(verbose_name='Valor')),
                ('valor_corrigido', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('pagamento', models.DateField(auto_now_add=True, verbose_name='Data de Pagamento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Contas',
            },
        ),
    ]
